#!/bin/bash
kali_tools_installer() {
    echo -e "\e[31minstalling Tools for kali\e[0m"
    
    #checking feroxbuster
    if ! command -v feroxbuster &>/dev/null; then
        echo "\e[31mferoxbuster is not installed. Installing feroxbuster...\e[0m"
        sudo apt install feroxbuster
    else
        echo -e "\e[32mferoxbuster is already installed...\e[0m"
    fi
    
    #checking if XSSstrike is downloaded or not
    xsstrike_DIR="$HOME/Tools/XSStrike"
    if [ -d "$xsstrike_DIR" ]; then
        echo -e "\e[32mXsstrike is already installed path is ~/Tools/XSStrike.\e[0m"
    else
        echo -e "\e[31mXSStrike not installed. Now installing XSStrike....\e[0m"
        cd ~/Tools
        git clone https://github.com/s0md3v/XSStrike.git
        cd XSStrike
        pip3 install -r requirements.txt
        chmod +x xsstrike.py
        echo -e "\e[32mXSStrike is now installed in ~/Tools\e[0m"
    fi
    
    #checking if sqlmap installed or not
    if ! command -v sqlmap &>/dev/null; then
        echo -e "\e[31msqlmap is not there. Now installng sqlmap...\e[0m"
        sudo apt install sqlmap
    else
        echo -e "\e[32msqlmap is already installed...\e[0m "
    fi
    
    #checking if ghauri is installed or not
    if ! command -v ghauri &>/dev/null; then
        echo -e "\e[31mghauri is not installed. Now installing ghauri....\e[0m"
        cd ~/Tools
        git clone https://github.com/r0oth3x4/ghauri.git
        cd ghauri
        pip3 install -r requirements.txt
        python3 setup.py build
        sudo python3 setup.py install
    else
        echo -e "\e[32mghauri is already installed \e[0m"
    fi
    
    #checking if waymore installed or not
    if ! command -v waymore &>/dev/null; then
        echo -e "\e[31mparamspier is not installed. Now installing paramspider...\e[0m"
        cd ~/Tools
        git clone https://github.com/devanshbatham/ParamSpider.git
        cd ParamSpider/
        python3 setup.py build
        sudo python3 setup.py install
    else
        echo -e "\e[32mparamspider is already installed..\e[0m"
    fi
    
    #checking if creepy crawler installed or not
    creepyCrawler_DIR=$HOME/Tools/creepyCrawler
    if [ -d "$creepyCrawler_DIR" ]; then
        echo -e "\e[32mcreepyCrawler already exist\e[0m"
    else
        echo -e "\e[31mNow installing creepyCrawler...\e[0m"
        cd ~/Tools
        git clone https://github.com/chm0dx/creepyCrawler.git
        cd creepyCrawler
        pip3 install -r requirements.txt
        chmod +x creepyCrawler.py
    fi
    
    #checkig if ffuf installed or not
    if ! command -v ffuf &>/dev/null; then
        echo -e "\e[31mffuf not installed. Now installing ffuf\e[0m"
        sudo apt install ffuf
    else
        echo -e "\e[32mffuf already installed...\e[0m"
    fi
    
    #checking if SSRFmap installed or not
    ssrf_DIR=$HOME/Tools/SSRFmap
    if [ -d "$ssrf_DIR" ]; then
        echo -e "\e[32mSSRFmap already installed..\e[0m"
    else
        echo -e "\e[31mssrf is now installing...\e[0m"
        cd ~/Tools
        git clone https://github.com/swisskyrepo/SSRFmap.git
        cd SSRFmap
        pip3 install -r requirements.txt
        chmod +x ssrfmap.py
    fi
    
    #checking wpscan
    if ! command -v wpscan &>/dev/null; then
        
        echo -e "\e[31mNow installing wpscan\e[0m"
        sudo apt install gem
        sudo apt install ruby
        sudo apt install build-essential libcurl4-openssl-dev libxml2 libxml2-dev libxslt1-dev ruby-dev libgmp-dev zlib1g-dev
        sudo gem install wpscan
        echo -e "\e[32mWpscan installed u good to go\e[0m
        "
    else
        echo -e "\e[32mWpscan is already installed\e[0m"
    fi
    
    #calling go tool for installetion
    cd $TARGET
    exec installers/go_tool_installer
}
#calling the fum=nction
kali_tools_installer