#!/bin/bash

Tool_for_ubuntu() {
    #feroxbuster
    if ! command -v feroxbuster &>/dev/null; then
        echo -e "\e[31mferoxbuster is not installed. Installing feroxbuster...\e[0m"
        cd ~/Tools
        wget https://github.com/epi052/feroxbuster/releases/download/v2.10.4/x86_64-linux-feroxbuster.tar.gz
        tar -xf x86_64-linux-feroxbuster.tar.gz
        chmod +x feroxbuster
        sudo cp feroxbuster /bin
        cd ~/Tools
        rm -rf feroxbuster x86_64-linux-feroxbuster.tar.gz
    else
        echo -e "\e[32mferoxbuster is already installed...\e[0m"
    fi

    #XSSstrike
    xsstrike_DIR="$HOME/Tools/XSStrike"
    if [ -d "$xsstrike_DIR" ]; then
        echo -e "\e[32mXsstrike is already installed path is ~/Tools/XSStrike.\e[0m"
    else
        echo -e "\e[32mXSStrike not installed. Now installing XSStrike....\e[0m"
        cd ~/Tools
        git clone https://github.com/s0md3v/XSStrike.git
        cd XSStrike
        pip3 install -r requirements.txt
        chmod +x xsstrike.py
        echo -e "\e[31mXSStrike is now installed in ~/Tools\e[0m"
    fi

    #sqlmap
    sqlmap_DIR="$HOME/Tools/sqlmap"
    if [ -d "$sqlmap_DIR" ]; then
        echo -e "\e[32msqlmap is already installed path is ~/Tools/sqlmap\e[0m"
    else
        echo -e "\e[31mnow installing sqlmap....\e0m"
        cd ~/Tools
        git clone https://github.com/sqlmapproject/sqlmap.git
    fi

    #ghauri
    if ! command -v ghauri &>/dev/null; then
        echo -e "\e[31mghauri is not installed. Now installing ghauri....\e[0m"
        cd ~/Tools
        git clone https://github.com/r0oth3x49/ghauri.git
        cd ghauri
        pip3 install -r requirements.txt
        python3 setup.py build
        sudo python3 setup.py install
    else
        echo -e "\e[32mghauri is already installed\e[0m"
    fi

    #checking if waymore installed or not
    if ! command -v waymore &>/dev/null; then
        echo -e "\e[31mwaymore is not installed. Now installing waymore...\e[0m"
        cd ~/Tools
        git clone https://github.com/xnl-h4ck3r/waymore.git
        cd waymore/
        pip3 install -r requirements.txt
        python3 setup.py build
        sudo python3 setup.py install
    else
        echo -e "\e[32mwaymore is already installed\e[0m"
    fi

    #checkinng if paramspider installed or not
    if ! command -v paramspider &>/dev/null; then
        echo -e "\e[31mparamspier is not installed. Now installing para,spider...\e[0m"
        cd ~/Tools
        git clone https://github.com/devanshbatham/ParamSpider.git
        cd ParamSpider/
        python3 setup.py build
        sudo python3 setup.py install
    else
        echo -e "\e[32mparamspider is already installed..\e[0m"
    fi

    #checking if creepy crawler installed or not
    ccreepyCrawler_DIR=$HOME/Tools/creepyCrawler
    if [ -d "$ccreepyCrawler_DIR" ]; then
        echo -e "\e[32mcreepyCrawler already exist\e[0m"
    else
        echo "Now installing creepyCrawler..."
        cd ~/Tools
        git clone https://github.com/chm0dx/creepyCrawler.git
        cd creepyCrawler
        pip3 install -r requirements.txt
        chmod +x creepyCrawler.py
    fi

    #checkig if ffuf installed or not
    if ! command -v ffuf &>/dev/null; then
        echo -e "\e[31mffuf not installed. Now installing ffuf\3[0m"
        sudo apt install ffuf
    else
        echo -e "\e[32mffuf already installed...\e[0m"
    fi

    #checking if SSRFmap installed or not
    ssrf_DIR=$HOME/Tools/SSRFmap
    if [ -d "$ssrf_DIR" ]; then
        echo -e "\e[32mSSRFmap already installed...\e[0m"
    else
        echo -e "\e[31meSSRFmap Now installing....\e[0m]"
        cd ~/Tools
        git clone https://github.com/swisskyrepo/SSRFmap.git
        cd SSRFmap
        pip install -r requirements.txt
        chmod +x ssrfmap.py
    fi

    #seclists
    seclist_DIR=/usr/share/seclists
    if [ -d "$seclist_DIR" ]; then
        echo -e "\e[32mseclist is already installed path is /usr/share/seclists\e[0m"
    else
        echo -e "\e[31mNow Installing seclists....\e[0m"
        cd ~/Tools
        git clone https://github.com/danielmiessler/SecLists.git
        mv SecLists seclists
        sudo cp -r seclists /usr/share
        rm -rf seclists
    fi

    #metasploit
    if ! command -v msfvenom &>/dev/null; then
        echo -e "\e[31mNow installing metasploit....\e[0m"
        cd ~/Tools
        curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb >msfinstall && chmod 755 msfinstall && ./msfinstall
    else
        echo -e "\e[32mmetasploit is already installed\e[0m"
    fi

    #checking wpscan
    if ! command -v wpscan &>/dev/null; then
        echo -e "\e[31mNow installing wpscan\e[0m"
        sudo apt install -y ruby gem build-essential libcurl4-openssl-dev libxml2 libxml2-dev libxslt1-dev ruby-dev libgmp-dev zlib1g-dev
        sudo gem install wpscan
        echo -e "\e[32mWpscan installed u good to go\e[0m
        "
        ./installers/go_tool_installer.sh
    else
        echo -e "\e[32mWpscan is already installed\e[0m"
        ./installers/go_tool_installer.sh

    fi

    # calling go tool for installetion
    # ./installers/go_tool_installer.sh
}
Tool_for_ubuntu
