#!/bin/bash

Tool_for_ubuntu() {
    #feroxbuster
    if ! command -v feroxbuster &>/dev/null; then
        echo -e "\e[31mferoxbuster is not installed. Installing feroxbuster...\e[0m"
        wget https://github.com/epi052/feroxbuster/releases/download/v2.10.4/x86_64-linux-feroxbuster.tar.gz -o ~/Tools
        tar -xf ~/Tools/x86_64-linux-feroxbuster.tar.gz
        chmod +x ~/Tools/feroxbuster
        sudo mv ~/Tools/feroxbuster /bin
        # rm -rf ~/Tools/feroxbuster ~/Tools/x86_64-linux-feroxbuster.tar.gz
    else
        echo -e "\e[32mferoxbuster is already installed...\e[0m"
    fi

    #XSSstrike
    xsstrike_DIR="$HOME/Tools/XSStrike"
    if [ -d "$xsstrike_DIR" ]; then
        echo -e "\e[32mXsstrike is already installed path is ~/Tools/XSStrike.\e[0m"
    else
        echo -e "\e[32mXSStrike not installed. Now installing XSStrike....\e[0m"
        git clone https://github.com/s0md3v/XSStrike.git ~/Tools
        pip3 install -r ~/Tools/requirements.txt
        chmod +x ~/Tools/XSStrike/XSStrike/xsstrike.py
        echo -e "\e[31mXSStrike is now installed in ~/Tools\e[0m"
    fi

    #sqlmap
    sqlmap_DIR="$HOME/Tools/sqlmap"
    if [ -d "$sqlmap_DIR" ]; then
        echo -e "\e[32msqlmap is already installed path is ~/Tools/sqlmap\e[0m"
    else
        echo -e "\e[31mnow installing sqlmap....\e0m"
        git clone https://github.com/sqlmapproject/sqlmap.git ~/Tools
    fi

    #ghauri
    if ! command -v ghauri &>/dev/null; then
        echo -e "\e[31mghauri is not installed. Now installing ghauri....\e[0m"
        git clone https://github.com/r0oth3x49/ghauri.git ~/Tools
        pip3 install -r ~/Tools/ghauri/requirements.txt
        python3 ~/Tools/ghauri/setup.py build
        sudo python3 ~/Tools/ghauri/setup.py install
    else
        echo -e "\e[32mghauri is already installed\e[0m"
    fi

    #checking if waymore installed or not
    if ! command -v waymore &>/dev/null; then
        echo -e "\e[31mwaymore is not installed. Now installing waymore...\e[0m"
        git clone https://github.com/xnl-h4ck3r/waymore.git ~/Tools
        pip3 install -r ~/Tools/waymore/requirements.txt
        python3 ~/Tools/waymore/setup.py build
        sudo python3 ~/Tools/waymore/setup.py install
    else
        echo -e "\e[32mwaymore is already installed\e[0m"
    fi

    #checkinng if paramspider installed or not
    if ! command -v paramspider &>/dev/null; then
        echo -e "\e[31mparamspier is not installed. Now installing para,spider...\e[0m"
        git clone https://github.com/devanshbatham/ParamSpider.git ~/Tools
        python3 ~/Tools/ParamSpider/setup.py build
        sudo python3 ~/Tools/ParamSplider/setup.py install
    else
        echo -e "\e[32mparamspider is already installed..\e[0m"
    fi

    #checking if creepy crawler installed or not
    ccreepyCrawler_DIR=$HOME/Tools/creepyCrawler
    if [ -d "$ccreepyCrawler_DIR" ]; then
        echo -e "\e[32mcreepyCrawler already exist\e[0m"
    else
        echo "Now installing creepyCrawler..."
        git clone https://github.com/chm0dx/creepyCrawler.git ~/Tools
        pip3 install -r ~/Tools/creepyCrawler/requirements.txt
        chmod +x ~/Tools/creepyCrawler/creepyCrawler.py
    fi

    #checkig if ffuf installed or not
    if ! command -v ffuf &>/dev/null; then
        echo -e "\e[31mffuf not installed. Now installing ffuf\3[0m"
        sudo apt install ffuf
    else
        echo -e "\e[32mffuf already installed...\e[0m"
    fi

    #checking if SSRFmap installed or not
    ssrf_DIR=$HOME/Tools/SSRFmap
    if [ -d "$ssrf_DIR" ]; then
        echo -e "\e[32mSSRFmap already installed...\e[0m"
    else
        echo -e "\e[31meSSRFmap Now installing....\e[0m]"
        git clone https://github.com/swisskyrepo/SSRFmap.git ~/Tools
        pip install -r ~/Tools/SSRFmap/requirements.txt
        chmod +x ~/Tools/SSRFmap/ssrfmap.py
    fi

    #seclists
    seclist_DIR=/usr/share/seclists
    if [ -d "$seclist_DIR" ]; then
        echo -e "\e[32mseclist is already installed path is /usr/share/seclists\e[0m"
    else
        echo -e "\e[31mNow Installing seclists....\e[0m"
        git clone https://github.com/danielmiessler/SecLists.git ~/Tools
        mv ~/Tools/SecLists ~/Tools/seclists
        sudo cp -r ~/Tools/seclists /usr/share
        rm -rf seclists
    fi

    #metasploit
    if ! command -v msfvenom &>/dev/null; then
        echo -e "\e[31mNow installing metasploit....\e[0m"
        curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb  >~/Tools/msfinstall && chmod 755 ~/Tools/msfinstall && ./Tools/msfinstall
    else
        echo -e "\e[32mmetasploit is already installed\e[0m"
    fi

    #checking wpscan
    if ! command -v wpscan &>/dev/null; then
        echo -e "\e[31mNow installing wpscan\e[0m"
        sudo apt install -y ruby gem build-essential libcurl4-openssl-dev libxml2 libxml2-dev libxslt1-dev ruby-dev libgmp-dev zlib1g-dev
        sudo gem install wpscan
        echo -e "\e[32mWpscan installed u good to go\e[0m
        "
    else
        echo -e "\e[32mWpscan is already installed\e[0m"
    fi

    # calling go tool for installetion
    ./installers/go_tool_installer.sh
}
Tool_for_ubuntu
